version: "3"
services:
  app:
    image: macarooniman/buddyservers:latest
    container_name: buddyservers
    stdin_open: true
    tty: true
    restart: unless-stopped

    environment:

      # Default web interface port
      WEB_PORT: "8080"

      # Change the web interface credentials
      WEB_USERNAME: "root"
      WEB_PASSWORD: "buddyservers"

    ports:

      # Web interface (make this the same as WEB_PORT)
      - "8080:8080"

      # Telepath API (buddyservers)
      - "7001:7001"

      # Add more ports based on the servers you create
      - "25565:25565"

    volumes:
      - buddyservers-data:/root/.buddyservers

volumes:
  buddyservers-data:
